sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  #aliyunOss配置
  alioss:
      endpoint: https://oss-cn-chengdu.aliyuncs.com
<<<<<<< HEAD
      accessKeyId: LTAI5tNpQXougajoA9oXm1rg
      accessKeySecret: SG4Z7bH59qgWNWQF9D8PagBtUD4VxE
      bucketName: niki-springweb
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
=======
      accessKeyId:  xxxxxxxxxxxxx
      accessKeySecret: xxxxxxxxxxxxx
      bucketName:   xxxxxxxxxx
>>>>>>> caa1bf6fe073216dbc199cf2c92a5502508c33f2
